# Import from text file from Lotus to VI-SuspensionGen

# Modules
import numpy as np

# Ask for user inputs

print("Lotus to VI-SuspensionGen L.U.C.A.")
sourcefile = input("Source file name: ")
suspName = input("VI-SuspensionGen suspension name: ")
axle = input("Please write if front or rear suspension (lowercase): ")
destfile = input("Output file name: ")

S = np.loadtxt(sourcefile,delimiter='\t',skiprows=0)

D = open(destfile,"w")  #write mode

D.write("assemblyName\tAssemblyDoubleWishBone")
D.write("\nlonPosType\t" + axle)
D.write("\nunitsFile")
D.write("\n                   length\tmm")
D.write("\n                    force\tnewton")
D.write("\nend")
D.write("\nleftSuspFile")
D.write("\n                 suspType\tDoubleWishBone")
D.write("\n                 suspName\t" + suspName)
D.write("\n              wheelCenter\t" + str(S[13][1]) + "\t" + str(S[13][2]) + "\t" + str(S[13][3]))
D.write("\n                 ucaFront\t" + str(S[3][1]) + "\t" + str(S[3][2]) + "\t" + str(S[3][3]))
D.write("\n                  ucaRear\t" + str(S[4][1]) + "\t" + str(S[4][2]) + "\t" + str(S[4][3]))
D.write("\n                 ucaOuter\t" + str(S[5][1]) + "\t" + str(S[5][2]) + "\t" + str(S[5][3]))
D.write("\n                 lcaFront\t" + str(S[0][1]) + "\t" + str(S[0][2]) + "\t" + str(S[0][3]))
D.write("\n                  lcaRear\t" + str(S[1][1]) + "\t" + str(S[1][2]) + "\t" + str(S[1][3]))
D.write("\n                 lcaOuter\t" + str(S[2][1]) + "\t" + str(S[2][2]) + "\t" + str(S[2][3]))
D.write("\n              tierodOuter\t" + str(S[8][1]) + "\t" + str(S[8][2]) + "\t" + str(S[8][3]))
D.write("\n              tierodInner\t" + str(S[9][1]) + "\t" + str(S[9][2]) + "\t" + str(S[9][3]))
D.write("\n         springUpperMount\t" + str(S[10][1]) + "\t" + str(S[10][2]) + "\t" + str(S[10][3]))
D.write("\n         springLowerMount\t" + str(S[11][1]) + "\t" + str(S[11][2]) + "\t" + str(S[11][3]))
D.write("\n         damperUpperMount\t" + str(S[10][1]) + "\t" + str(S[10][2]) + "\t" + str(S[10][3]))
D.write("\n         damperLowerMount\t" + str(S[11][1]) + "\t" + str(S[11][2]) + "\t" + str(S[11][3]))
D.write("\n                  arbLink\t" + "0" + "\t" + "0" + "\t" + "0")
D.write("\n                 toeAngle\t" + "0")
D.write("\n              camberAngle\t" + "0")
D.write("\n               steerRatio\t" + "-0.14167")
D.write("\n             groundHeigth\t" + "0")
D.write("\n              wheelRadius\t" + "331")
D.write("\n               wheelWidth\t" + "305")
D.write("\n                 toeSetup\t" + "0")
D.write("\n              camberSetup\t" + "0")
D.write("\n              casterSetup\t" + "0")
D.write("\n               rideHeigth\t" + "0")
D.write("\n                  kSpring\t" + "100")
D.write("\n            springPreload\t" + "3620")
D.write("\n                 cgHeight\t" + "380")
D.write("\n                wheelBase\t" + "2700")
D.write("\n               driveRatio\t" + "0")
D.write("\n               brakeRatio\t" + "75")
D.write("\n               springType\t" + "0")
D.write("\n         springAttachment\t" + "1")
D.write("\n    tierodInnerAttachment\t" + "0")
D.write("\n                  cDamper\t" + "10")
D.write("\n    rideHeightRefPosition\t" + "1")
D.write("\n            arbAttachment\t" + "2")
D.write("\n                kUcaFront\t" + "875040\t875040\t875040\t64736\t64736\t0\t87.753\t90\t270")
D.write("\n                 kUcaRear\t" + "875040\t875040\t875040\t64736\t64736\t0\t267.753\t90\t90")
D.write("\n                kLcaFront\t" + "875040\t875040\t875040\t64736\t64736\t0\t88.238\t90\t270")
D.write("\n                 kLcaRear\t" + "875040\t875040\t875040\t64736\t64736\t0\t268.238\t90\t90")
D.write("\n             kTierodInner\t" + "1000000\t1000000\t1000000\t10\t10\t10\t180\t90\t180")
D.write("\nend")
D.write("\nrightSuspFile")
D.write("\n                     symm")
D.write("\nend")
D.write("\naRollFile")
D.write("\n                aRollType\t" + "AntiRollBar")
D.write("\n                aRollName\t" + "TestAR")
D.write("\n               lonPosType\t" + axle)
D.write("\n               bendARLeft\t" + "0" + "\t" + "0" + "\t" + "0")
D.write("\n               dropARLeft\t" + "0" + "\t" + "0" + "\t" + "0")
D.write("\n              bendARRight\t" + "0" + "\t" + "0" + "\t" + "0")
D.write("\n              dropARRight\t" + "0" + "\t" + "0" + "\t" + "0")
D.write("\n                 kTorsion\t" + "0")
D.write("\n             kTorsionType\t" + "0")
D.write("\nend")
D.write("\nanalysisFile")
D.write("\n                    setup\t" + "0")
D.write("\n                      kin\t" + "1")
D.write("\n              jounceStart\t" + "-60")
D.write("\n                jounceEnd\t" + "60")
D.write("\n                  nJounce\t" + "12")
D.write("\n               steerStart\t" + "-360")
D.write("\n                 steerEnd\t" + "360")
D.write("\n                   nSteer\t" + "18")
D.write("\n              forceXStart\t" + "-3500")
D.write("\n                forceXEnd\t" + "3500")
D.write("\n              forceYStart\t" + "-3500")
D.write("\n                forceYEnd\t" + "3500")
D.write("\n             momentZStart\t" + "-500000")
D.write("\n               momentZEnd\t" + "500000")
D.write("\n                   nForce\t" + "8")
D.write("\n              deltaJounce\t" + "60")
D.write("\n                    nRoll\t" + "12")
D.write("\n               outputFile\t" + "output")
D.write("\nend")

D.close()
