# Import from text file from Lotus to VI-SuspensionGen

# Modules
import numpy as np

# Ask for user inputs

sourcefile = input("Source file name: ")
suspName = input("VI-SuspensionGen suspension name: ")
axle = input("Please write if front or rear suspension (lowercase): ")
destfile = input("Output file name: ")

S = np.loadtxt(sourcefile,delimiter='\t',skiprows=0)

D = open(destfile,"w")  #write mode

D.write("assemblyName\tAssemblyDoubleWishBonePRUBar")
D.write("\nlonPosType\t" + axle)
D.write("\nunitsFile")
D.write("\n                   length\tmm")
D.write("\n                    force\tnewton")
D.write("\nend")
D.write("\nleftSuspFile")
D.write("\n                 suspType\tDoubleWishBonePR")
D.write("\n                 suspName\t" + suspName)
D.write("\n              wheelCenter\t" + str(S[13][1]) + "\t" + str(S[13][2]) + "\t" + str(S[13][3]))
D.write("\n                 ucaFront\t" + str(S[3][1]) + "\t" + str(S[3][2]) + "\t" + str(S[3][3]))
D.write("\n                  ucaRear\t" + str(S[4][1]) + "\t" + str(S[4][2]) + "\t" + str(S[4][3]))
D.write("\n                 ucaOuter\t" + str(S[5][1]) + "\t" + str(S[5][2]) + "\t" + str(S[5][3]))
D.write("\n                 lcaFront\t" + str(S[0][1]) + "\t" + str(S[0][2]) + "\t" + str(S[0][3]))
D.write("\n                  lcaRear\t" + str(S[1][1]) + "\t" + str(S[1][2]) + "\t" + str(S[1][3]))
D.write("\n                 lcaOuter\t" + str(S[2][1]) + "\t" + str(S[2][2]) + "\t" + str(S[2][3]))
D.write("\n              tierodOuter\t" + str(S[8][1]) + "\t" + str(S[8][2]) + "\t" + str(S[8][3]))
D.write("\n              tierodInner\t" + str(S[9][1]) + "\t" + str(S[9][2]) + "\t" + str(S[9][3]))
D.write("\n             pushrodOuter\t" + str(S[6][1]) + "\t" + str(S[6][2]) + "\t" + str(S[6][3]))
D.write("\n             pushrodInner\t" + str(S[7][1]) + "\t" + str(S[7][2]) + "\t" + str(S[7][3]))
D.write("\n              rockerPivot\t" + str(S[14][1]) + "\t" + str(S[14][2]) + "\t" + str(S[14][3]))
D.write("\n          rockerPivotAxis\t" + str(S[15][1]) + "\t" + str(S[15][2]) + "\t" + str(S[15][3]))
D.write("\n               rockerLink\t" + str(S[44][1]) + "\t" + str(S[44][2]) + "\t" + str(S[44][3]))
D.write("\n         springUpperMount\t" + str(S[10][1]) + "\t" + str(S[10][2]) + "\t" + str(S[10][3]))
D.write("\n         springLowerMount\t" + str(S[11][1]) + "\t" + str(S[11][2]) + "\t" + str(S[11][3]))
D.write("\n         damperUpperMount\t" + str(S[10][1]) + "\t" + str(S[10][2]) + "\t" + str(S[10][3]))
D.write("\n         damperLowerMount\t" + str(S[11][1]) + "\t" + str(S[11][2]) + "\t" + str(S[11][3]))
D.write("\nrockerLinkToCentralSpring\t" + "0\t0\t0")
D.write("\nrockerLinkToCentralDamper\t" + "0\t0\t0")
D.write("\n   rockerLinkToRollDamper\t" + "0\t0\t0")
D.write("\n      rockerLinkToInerter\t" + "0\t0\t0")
D.write("\n                 toeAngle\t" + "0")
D.write("\n              camberAngle\t" + "0")
D.write("\n               steerRatio\t" + "0.1256")
D.write("\n             groundHeigth\t" + "0")
D.write("\n              wheelRadius\t" + "317")
D.write("\n               wheelWidth\t" + "270")
D.write("\n                 toeSetup\t" + "0")
D.write("\n              camberSetup\t" + "0")
D.write("\n                pinHeigth\t" + "177.5")
D.write("\n               rideHeigth\t" + "0")
D.write("\n                  kSpring\t" + "100")
D.write("\n            springPreload\t" + "1000")
D.write("\n                 cgHeight\t" + "340")
D.write("\n                wheelBase\t" + "2340")
D.write("\n               driveRatio\t" + "0")
D.write("\n               brakeRatio\t" + "60")
D.write("\n           pRodAttachment\t" + "2")
D.write("\n               springType\t" + "0")
D.write("\n         springAttachment\t" + "3")
D.write("\n                  cDamper\t" + "10")
D.write("\n    rideHeightRefPosition\t" + "1")
D.write("\n                kUcaFront\t" + "875040\t875040\t875040\t64736\t64736\t0\t87.753\t90\t270")
D.write("\n                 kUcaRear\t" + "875040\t875040\t875040\t64736\t64736\t0\t267.753\t90\t90")
D.write("\n                kLcaFront\t" + "875040\t875040\t875040\t64736\t64736\t0\t88.238\t90\t270")
D.write("\n                 kLcaRear\t" + "875040\t875040\t875040\t64736\t64736\t0\t268.238\t90\t90")
D.write("\n             kTierodInner\t" + "1000000\t1000000\t1000000\t10\t10\t10\t180\t90\t180")
D.write("\nend")
D.write("\nrightSuspFile")
D.write("\n                     symm")
D.write("\nend")
D.write("\naRollFile")
D.write("\n                aRollType\t" + "AntiRollBar")
D.write("\n                aRollName\t" + "TestAR")
D.write("\n               lonPosType\t" + axle)
D.write("\n               bendARLeft\t" + str(S[48][1]) + "\t" + str(S[48][2]) + "\t" + str(S[48][3]))
D.write("\n               dropARLeft\t" + str(S[46][1]) + "\t" + str(S[46][2]) + "\t" + str(S[46][3]))
D.write("\n              bendARRight\t" + str(S[48][1]) + "\t" + str(-1*S[48][2]) + "\t" + str(S[48][3]))
D.write("\n              dropARRight\t" + str(S[46][1]) + "\t" + str(-1*S[46][2]) + "\t" + str(S[46][3]))
D.write("\n                 kTorsion\t" + "0")
D.write("\n             kTorsionType\t" + "0")
D.write("\nend")
D.write("\nanalysisFile")
D.write("\n                    setup\t" + "0")
D.write("\n                      kin\t" + "1")
D.write("\n              jounceStart\t" + "-60")
D.write("\n                jounceEnd\t" + "60")
D.write("\n                  nJounce\t" + "16")
D.write("\n               steerStart\t" + "-360")
D.write("\n                 steerEnd\t" + "360")
D.write("\n                   nSteer\t" + "16")
D.write("\n              forceXStart\t" + "-3500")
D.write("\n                forceXEnd\t" + "3500")
D.write("\n              forceYStart\t" + "-3500")
D.write("\n                forceYEnd\t" + "3500")
D.write("\n             momentZStart\t" + "-500000")
D.write("\n               momentZEnd\t" + "500000")
D.write("\n                   nForce\t" + "8")
D.write("\n              deltaJounce\t" + "60")
D.write("\n                    nRoll\t" + "16")
D.write("\n               outputFile\t" + "output")
D.write("\nend")

D.close()
